# Generated by Django 3.2.8 on 2021-11-17 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_boat_boat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='boat_image',
        ),
    ]
