# Generated by Django 3.2.9 on 2021-11-17 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='boat_image',
            field=models.ImageField(blank=True, default='no_image.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter', to=settings.AUTH_USER_MODEL),
        ),
    ]
