# Generated by Django 3.2.9 on 2021-11-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_rent_renter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='boat_image',
            field=models.ImageField(blank=True, default='images/no_image.jpg', null=True, upload_to='images/'),
        ),
    ]
