# Generated by Django 3.2.9 on 2021-11-17 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_boat_boat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 11, 18)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 11, 18)),
        ),
    ]
